### ISSUE TITLE
computing percentage similarity

### ISSUE THREAD

**Issue by Hareem-E-Sahar** [SAG-KeLP/kelp-additional-kernels#2]
Kelp tree kernels count number of common trees to calculate similarity and then report its value. Is there a way to compute percentage similarity while still using the kernelComputation() function?

**Comment by SimoneFilice** [comment]
Hi,

This is probably what you are looking for: http://www.kelp-ml.org/kelp-javadoc/current-version/it/uniroma2/sag/kelp/kernel/standard/NormalizationKernel.html

Best,
Simone
